env:
  browser: true
  es2021: true
  node: true
parser: "babel-eslint"
settings:
  react:
    version: detect
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "prettier"
parserOptions:
  ecmaFeatures:
    jsx: false
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  {
    react/prop-types: "off",
    react/react-in-jsx-scope: "off",
    react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }],
  }
